# config/trainer/callbacks/base.yaml

# config/trainer/callbacks/base.yaml

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  filename: "${model.name}-{epoch:02d}-{val_loss:.4f}"
  dirpath: ${paths.checkpoints_dir}

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss"
  mode: "min"
  patience: 10

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"


# Keras Callbacks
# model_checkpoint:
#   _target_: tensorflow.keras.callbacks.ModelCheckpoint
#   filepath: "${paths.checkpoints_dir}/${model.name}-{epoch:02d}-{val_loss:.4f}.h5"
#   monitor: "val_loss"
#   mode: "min"
#   save_best_only: true
#   verbose: 1

# early_stopping:
#   _target_: tensorflow.keras.callbacks.EarlyStopping
#   monitor: "val_loss"
#   mode: "min"
#   patience: 10
#   verbose: 1
